image: fedora:rawhide

variables:
  DEPENDENCIES_GRILO: gobject-introspection-devel libxml2-devel
                      libsoup-devel glib2-devel gtk3-devel
                      liboauth-devel totem-pl-parser-devel
                      meson redhat-rpm-config gcc gcc-c++ glibc-devel git vala
                      gtk-doc

  DEPENDENCIES: sqlite-devel libgcrypt-devel itstool lua-devel
                libsoup-devel gperf libarchive-devel json-glib-devel
                avahi-gobject-devel totem-pl-parser-devel rest-devel
                tracker-devel libdmapsharing-devel libmediaart-devel
                gom-devel gnome-online-accounts-devel libgdata-devel
                gstreamer1-plugins-good gstreamer1-plugins-bad-free-extras

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
  script:
    - dnf install -y --nogpgcheck $DEPENDENCIES_GRILO $DEPENDENCIES
    # FIXME until stable
    - rpm -Uvh https://kojipkgs.fedoraproject.org//packages/gom/0.4/1.fc33/x86_64/gom-0.4-1.fc33.x86_64.rpm
      https://kojipkgs.fedoraproject.org//packages/gom/0.4/1.fc33/x86_64/gom-devel-0.4-1.fc33.x86_64.rpm
    # As part of configuring grilo-plugins.git for build, the latest code from
    # grilo.git will be fetched by Meson and it will be built as a subproject.
    - meson . _build --prefix=/usr
      -Denable-bookmarks=yes
      -Denable-chromaprint=yes
      -Denable-dleyna=yes
      -Denable-dmap=yes
      -Denable-filesystem=yes
      -Denable-flickr=yes
      -Denable-freebox=yes
      -Denable-gravatar=yes
      -Denable-jamendo=yes
      -Denable-local-metadata=yes
      -Denable-lua-factory=yes
      -Denable-magnatune=yes
      -Denable-metadata-store=yes
      -Denable-opensubtitles=yes
      -Denable-optical-media=yes
      -Denable-podcasts=yes
      -Denable-raitv=yes
      -Denable-shoutcast=yes
      -Denable-thetvdb=yes
      -Denable-tmdb=yes
      -Denable-tracker=yes
      -Denable-vimeo=yes
      -Denable-youtube=yes
    - ninja -C _build
    - ninja -C _build install
    - meson test -C _build --suite=grilo-plugins
