image: fedora:rawhide

variables:
  DEPENDENCIES_GRILO: gobject-introspection-devel libxml2-devel
                      libsoup-devel glib2-devel gtk3-devel
                      liboauth-devel totem-pl-parser-devel
                      meson redhat-rpm-config gcc gcc-c++ glibc-devel git vala

  DEPENDENCIES: gtk-doc sqlite-devel libgcrypt-devel itstool lua-devel
                libsoup-devel gperf libarchive-devel json-glib-devel
                avahi-gobject-devel totem-pl-parser-devel rest-devel
                tracker-devel libdmapsharing-devel libmediaart-devel
                gom-devel gnome-online-accounts-devel libgdata-devel
                gstreamer1-plugins-good gstreamer1-plugins-bad-free-extras

build_stable:
  before_script:
    - dnf update -y --nogpgcheck
    - dnf install -y --nogpgcheck $DEPENDENCIES_GRILO
    # Build grilo from git, grilo and grilo-plugins must be in sync
    - git clone https://gitlab.gnome.org/GNOME/grilo.git
    - cd grilo
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
    - cd ..
  script:
    - dnf install -y --nogpgcheck $DEPENDENCIES
    - meson . _build --prefix=/usr
    - ninja -C _build
    - ninja -C _build install
    - ninja -C _build test
